version: "3.9"

services:
  postgresql:
    image: postgres:12.8-alpine  # Our version in AWS.
    container_name: pg-rewards-api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dimo
      - POSTGRES_PASSWORD=dimo
      - POSTGRES_DB=rewards_api
    volumes:
      - ./resources/data:/var/log/postgresql/data:delegated
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: es-rewards-api
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

networks:
  elastic:
    driver: bridge
