ENVIRONMENT: local
PORT: 3000
LOG_LEVEL: info
DB_USER: dimo
DB_PASSWORD: dimo
DB_PORT: 5432
DB_HOST: localhost
DB_NAME: rewards_api
DB_MAX_OPEN_CONNECTIONS: 5
DB_MAX_IDLE_CONNECTIONS: 5
SERVICE_NAME: rewards-api
JWT_KEY_SET_URL: http://127.0.0.1:5556/dex/keys
ELASTIC_SEARCH_ANALYTICS_HOST: http://localhost:9200
DEVICE_DATA_INDEX_NAME: device-status
META_TRANSACTION_SEND_TOPIC: topic.transaction.request.send
META_TRANSACTION_STATUS_TOPIC: topic.transaction.request.status
