ENVIRONMENT: local
PORT: 3000
LOG_LEVEL: info
DB:
  USER: dimo
  PASSWORD: dimo
  PORT: 5432
  HOST: localhost
  NAME: rewards_api
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
SERVICE_NAME: rewards-api
JWT_KEY_SET_URL: http://127.0.0.1:5556/dex/keys
ELASTIC_SEARCH_ANALYTICS_HOST: http://localhost:9200
DEVICE_DATA_INDEX_NAME: device-status
META_TRANSACTION_SEND_TOPIC: topic.transaction.request.send
META_TRANSACTION_STATUS_TOPIC: topic.transaction.request.status
KAFKA_BROKERS: localhost:9092
CONSUMER_GROUP: rewards-api
TRANSFER_BATCH_SIZE: 2
CONTRACT_EVENT_TOPIC: topic.contract.event
FIRST_AUTOMATED_WEEK: 44
DEVICES_API_GRPC_ADDR:
DEFINITIONS_API_GRPC_ADDR:
USERS_API_GRPC_ADDR:
EAS_SCHEMA: 0x20351f973fdec1478924c89dfa533d8f872defa108d9c3c6512267d7e7e5dbc2 #mumbai
ATTESTATION_RECIPIENT: 0xBe396b4B84a4139EA5C4dbaDde98AE8364eB21e8
ATTESTATION_CONTRACT: 0xaEF4103A04090071165F78D45D83A0C0782c2B2a
