name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
env:
  GOPRIVATE: github.com/DIMO-INC
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  golangci:
    name: lint
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: false
