FROM golang:1.25 AS build

RUN useradd -u 10001 dimo

WORKDIR /build
COPY . ./

RUN make build

FROM busybox AS package

LABEL maintainer="DIMO <hello@dimo.zone>"

WORKDIR /

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /build/bin/rewards-api /
COPY --from=build /build/migrations /migrations

USER dimo

EXPOSE 8080
EXPOSE 8888

ENTRYPOINT ["/rewards-api"]
