replicaCount: 2
image:
  repository: dimozone/rewards-api
  pullPolicy: IfNotPresent
  tag: 1.24.2
cronJob:
  enabled: true
  schedule: 0 5 * * 1
env:
  ENVIRONMENT: prod
  PORT: '8080'
  LOG_LEVEL: info
  DB_PORT: '5432'
  DB_NAME: rewards_api
  DB_MAX_OPEN_CONNECTIONS: '50'
  DB_MAX_IDLE_CONNECTIONS: '15'
  JWT_KEY_SET_URL: https://auth.dimo.zone/keys
  DEVICES_API_GRPC_ADDR: devices-api-prod:8086
  USERS_API_GRPC_ADDR: users-api-prod:8086
  ACCOUNTS_API_GRPC_ADDR: accounts-api-prod:8086
  DEFINITIONS_API_GRPC_ADDR: device-definitions-api-prod:8086
  FETCH_API_GRPC_ADDR: fetch-api-prod:8086
  ATTESTATION_API_GRPC_ADDR: attestation-api-prod:8086
  META_TRANSACTION_SEND_TOPIC: topic.transaction.request.send
  META_TRANSACTION_STATUS_TOPIC: topic.transaction.request.status
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
  CONSUMER_GROUP: rewards-api
  ISSUANCE_CONTRACT_ADDRESS: '0x8129f3cD3EBA82136Caf5aB87E2321c958Da5B63'
  TRANSFER_BATCH_SIZE: 100
  REFERRAL_CONTRACT_ADDRESS: '0x3a99A9c4997B710febd7696E73088Fd9e51f49a5'
  IDENTITY_QUERY_URL: http://identity-api-prod:8080/query
  ENABLE_STAKING: true
  DIMO_REGISTRY_CHAIN_ID: 137
  VEHICLE_NFT_ADDRESS: '0xbA5738a18d83D41847dfFbDC6101d37C69c9B0cF'
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '9'
    external-dns.alpha.kubernetes.io/hostname: rewards-api.dimo.zone
  hosts:
    - host: rewards-api.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
config:
  tokens:
    - chainId: 1
      address: '0x5fab9761d60419c9eeebe3915a8fa1ed7e8d2e1b'
      rpcUrl: $ETHEREUM_RPC_URL
    - chainId: 137
      address: '0xe261d618a959afffd53168cd07d12e37b26761db'
      rpcUrl: $POLYGON_RPC_URL
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
kafka:
  clusterName: kafka-prod-dimo-kafka
