replicaCount: 2
image:
  repository: dimozone/rewards-api
  pullPolicy: IfNotPresent
  tag: 0.3.1
cronJob:
  enabled: true
  schedule: 0 5 * * 1
env:
  ENVIRONMENT: prod
  PORT: '8080'
  LOG_LEVEL: info
  DB_PORT: '5432'
  DB_NAME: rewards_api
  DB_MAX_OPEN_CONNECTIONS: '50'
  DB_MAX_IDLE_CONNECTIONS: '15'
  SERVICE_NAME: rewards-api
  JWT_KEY_SET_URL: https://auth.dimo.zone/keys
  DEPLOYMENT_BASE_URL: https://rewards-api.dimo.zone
  DEVICE_DATA_INDEX_NAME: device-status-prod*
  DEVICES_API_GRPC_ADDR: devices-api-prod:8086
  DEFINITIONS_API_GRPC_ADDR: device-definitions-api-prod:8086
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '9'
    external-dns.alpha.kubernetes.io/hostname: rewards-api.dimo.zone
  hosts:
    - host: rewards-api.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
kafka:
  clusterName: kafka-prod-dimo-kafka
