basePath: /v1
definitions:
  github.com_DIMO-Network_rewards-api_internal_controllers.UserResponse:
    properties:
      devices:
        description: |-
          Devices is a list of the user's devices, together with some information about their
          connectivity.
        items:
          $ref: '#/definitions/github.com_DIMO-Network_rewards-api_internal_controllers.UserResponseDevice'
        type: array
      points:
        description: Points is the user's total number of points, across all devices
          and issuance weeks.
        example: 5000
        type: integer
      thisWeek:
        $ref: '#/definitions/github.com_DIMO-Network_rewards-api_internal_controllers.UserResponseThisWeek'
        description: ThisWeek describes the current issuance week.
    type: object
  github.com_DIMO-Network_rewards-api_internal_controllers.UserResponseDevice:
    properties:
      connectedThisWeek:
        description: |-
          ConnectedThisWeek is true if we've seen activity from the device during the current issuance
          week.
        example: true
        type: boolean
      connectionStreak:
        description: |-
          ConnectionStreak is what we consider the streak of the device to be. This may not literally
          be the number of consecutive connected weeks, because the user may disconnect for a week
          without penalty, or have the connection streak reduced after three weeks of inactivity.
        example: 4
        type: integer
      disconnectionStreak:
        description: |-
          DisconnectionStreak is the number of consecutive issuance weeks that the device has been
          disconnected. This number resets to 0 as soon as a device earns rewards for a certain week.
        example: 0
        type: integer
      id:
        description: ID is the user device ID used across all services.
        example: 27cv7gVTh9h4RJuTsmJHpBcr4I9
        type: string
      lastActive:
        description: LastActive is the last time we saw activity from the vehicle.
        example: "2022-04-12T09:23:01Z"
        type: string
      level:
        $ref: '#/definitions/github.com_DIMO-Network_rewards-api_internal_controllers.UserResponseLevel'
        description: Level is the level 1-4 of the device. This is fully determined
          by ConnectionStreak.
      points:
        description: Points is the total number of points that the device has earned
          across all weeks.
        example: 5000
        type: integer
    type: object
  github.com_DIMO-Network_rewards-api_internal_controllers.UserResponseLevel:
    properties:
      maxWeeks:
        type: integer
      minWeeks:
        type: integer
      number:
        type: integer
      streakPoints:
        type: integer
    type: object
  github.com_DIMO-Network_rewards-api_internal_controllers.UserResponseThisWeek:
    properties:
      end:
        description: End is the timestamp of the start of the next issuance week.
        example: "2022-04-18T05:00:00Z"
        type: string
      start:
        description: Start is the timestamp of the start of the issuance week.
        example: "2022-04-11T05:00:00Z"
        type: string
    type: object
  internal_controllers.UserResponse:
    properties:
      devices:
        description: |-
          Devices is a list of the user's devices, together with some information about their
          connectivity.
        items:
          $ref: '#/definitions/internal_controllers.UserResponseDevice'
        type: array
      points:
        description: Points is the user's total number of points, across all devices
          and issuance weeks.
        example: 5000
        type: integer
      thisWeek:
        $ref: '#/definitions/internal_controllers.UserResponseThisWeek'
        description: ThisWeek describes the current issuance week.
    type: object
  internal_controllers.UserResponseDevice:
    properties:
      connectedThisWeek:
        description: |-
          ConnectedThisWeek is true if we've seen activity from the device during the current issuance
          week.
        example: true
        type: boolean
      connectionStreak:
        description: |-
          ConnectionStreak is what we consider the streak of the device to be. This may not literally
          be the number of consecutive connected weeks, because the user may disconnect for a week
          without penalty, or have the connection streak reduced after three weeks of inactivity.
        example: 4
        type: integer
      disconnectionStreak:
        description: |-
          DisconnectionStreak is the number of consecutive issuance weeks that the device has been
          disconnected. This number resets to 0 as soon as a device earns rewards for a certain week.
        example: 0
        type: integer
      id:
        description: ID is the user device ID used across all services.
        example: 27cv7gVTh9h4RJuTsmJHpBcr4I9
        type: string
      lastActive:
        description: LastActive is the last time we saw activity from the vehicle.
        example: "2022-04-12T09:23:01Z"
        type: string
      level:
        $ref: '#/definitions/internal_controllers.UserResponseLevel'
        description: Level is the level 1-4 of the device. This is fully determined
          by ConnectionStreak.
      points:
        description: Points is the total number of points that the device has earned
          across all weeks.
        example: 5000
        type: integer
    type: object
  internal_controllers.UserResponseLevel:
    properties:
      maxWeeks:
        type: integer
      minWeeks:
        type: integer
      number:
        type: integer
      streakPoints:
        type: integer
    type: object
  internal_controllers.UserResponseThisWeek:
    properties:
      end:
        description: End is the timestamp of the start of the next issuance week.
        example: "2022-04-18T05:00:00Z"
        type: string
      start:
        description: Start is the timestamp of the start of the issuance week.
        example: "2022-04-11T05:00:00Z"
        type: string
    type: object
info:
  contact: {}
  title: DIMO Rewards API
  version: "1.0"
paths:
  /user:
    get:
      description: A summary of the user's rewards.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_controllers.UserResponse'
      security:
      - BearerAuth: []
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
