{{- if .Values.cronJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "rewards-api.fullname" . }}-calculate-rewards
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rewards-api.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote}}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            linkerd.io/inject: disabled
          {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
          labels:
            {{- include "rewards-api.selectorLabels" . | nindent 12 }}
        spec:
          initContainers:
          - name: weekly-rewards-calculation
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            command: ['sh', '-c', "/rewards-api calculate"]
            envFrom:
            - configMapRef:
                name: {{ include "rewards-api.fullname" . }}-config
            - secretRef:
                name: {{ include "rewards-api.fullname" . }}-secret
          containers:
          - name: completed
            image: busybox
            command: ['sh', '-c', 'echo "weekly rewards calculation completed"']
          restartPolicy: OnFailure
{{ end }}          
