{{- if .Values.referralsCronJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "rewards-api.fullname" . }}-issue-referral-bonus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rewards-api.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.referralsCronJob.schedule | quote}}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
          {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
        spec:
          containers:
          - name: weekly-rewards-calculation
            securityContext:
              {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            command: ['/bin/sh']
            args: ['-c', '/rewards-api issue-referral-bonus; CODE=$?; echo "weekly referrals calculation completed"; wget -q --post-data "hello=shutdown" http://localhost:4191/shutdown &> /dev/null; exit $CODE;']
            envFrom:
            - configMapRef:
                name: {{ include "rewards-api.fullname" . }}-config
            - secretRef:
                name: {{ include "rewards-api.fullname" . }}-secret
          restartPolicy: OnFailure
{{ end }}          
