apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "rewards-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/rewards/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/rewards/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/rewards/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/host
    secretKey: ELASTIC_SEARCH_ANALYTICS_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/username
    secretKey: ELASTIC_SEARCH_ANALYTICS_USERNAME
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/password
    secretKey: ELASTIC_SEARCH_ANALYTICS_PASSWORD
  {{- /* Very ugly, I'm sorry. */ }}
  {{- if eq .Release.Namespace "prod" }}
  - remoteRef:
    key: {{ .Release.Namespace }}/contract_event/rpc_url/ethereum
    secretKey: ETHEREUM_RPC_URL
  - remoteRef:
    key: {{ .Release.Namespace }}/contract_event/rpc_url/polygon
    secretKey: POLYGON_RPC_URL
  {{- else if eq .Release.Namespace "dev" }}
  - remoteRef:
    key: {{ .Release.Namespace }}/contract_event/rpc_url/mumbai
    secretKey: MUMBAI_RPC_URL
  {{- end }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "rewards-api.fullname" . }}-secret
    template:
      metadata: {}
