apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "rewards-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/rewards/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/rewards/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/rewards/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/host
    secretKey: ELASTIC_SEARCH_ANALYTICS_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/username
    secretKey: ELASTIC_SEARCH_ANALYTICS_USERNAME
  - remoteRef:
      key: {{ .Release.Namespace }}/devices/elastic/analytics/password
    secretKey: ELASTIC_SEARCH_ANALYTICS_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/ethereum/rpc_url
    secretKey: ETHEREUM_RPC_URL
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "rewards-api.fullname" . }}-secret
    template:
      metadata: {}
