name: gotest

on:
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Checkout
        uses: actions/checkout@v3

      - name: Tidy
        run: go mod tidy
          
      - name: Test
        run: go test -v ./...
  
