name: gotest

on:
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Checkout
        uses: actions/checkout@v4

      - name: Tidy
        run: go mod tidy
          
      - name: Test
        run: go test -v ./...
  
