name: gotest

on:
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
    runs-on: self-hosted

    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: go get -v ./...
          
      - name: Test
        run: go test -v ./...
  
