// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DeviceWeekRewards string
	IssuanceWeek      string
}{
	DeviceWeekRewards: "device_week_rewards",
	IssuanceWeek:      "issuance_week",
}
