// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Blacklist               string
	IssuanceWeeks           string
	MetaTransactionRequests string
	Overrides               string
	Rewards                 string
	TokenTransfers          string
}{
	Blacklist:               "blacklist",
	IssuanceWeeks:           "issuance_weeks",
	MetaTransactionRequests: "meta_transaction_requests",
	Overrides:               "overrides",
	Rewards:                 "rewards",
	TokenTransfers:          "token_transfers",
}
