// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	IssuanceWeeks string
	Rewards       string
}{
	IssuanceWeeks: "issuance_weeks",
	Rewards:       "rewards",
}
