// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// TokenTransfer is an object representing the database table.
type TokenTransfer struct {
	AddressFrom     []byte        `boil:"address_from" json:"address_from" toml:"address_from" yaml:"address_from"`
	AddressTo       []byte        `boil:"address_to" json:"address_to" toml:"address_to" yaml:"address_to"`
	Amount          types.Decimal `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	TransactionHash []byte        `boil:"transaction_hash" json:"transaction_hash" toml:"transaction_hash" yaml:"transaction_hash"`
	LogIndex        int           `boil:"log_index" json:"log_index" toml:"log_index" yaml:"log_index"`
	BlockTimestamp  time.Time     `boil:"block_timestamp" json:"block_timestamp" toml:"block_timestamp" yaml:"block_timestamp"`
	UpdatedAt       time.Time     `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	ChainID         string        `boil:"chain_id" json:"chain_id" toml:"chain_id" yaml:"chain_id"`

	R *tokenTransferR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L tokenTransferL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var TokenTransferColumns = struct {
	AddressFrom     string
	AddressTo       string
	Amount          string
	TransactionHash string
	LogIndex        string
	BlockTimestamp  string
	UpdatedAt       string
	ChainID         string
}{
	AddressFrom:     "address_from",
	AddressTo:       "address_to",
	Amount:          "amount",
	TransactionHash: "transaction_hash",
	LogIndex:        "log_index",
	BlockTimestamp:  "block_timestamp",
	UpdatedAt:       "updated_at",
	ChainID:         "chain_id",
}

var TokenTransferTableColumns = struct {
	AddressFrom     string
	AddressTo       string
	Amount          string
	TransactionHash string
	LogIndex        string
	BlockTimestamp  string
	UpdatedAt       string
	ChainID         string
}{
	AddressFrom:     "token_transfers.address_from",
	AddressTo:       "token_transfers.address_to",
	Amount:          "token_transfers.amount",
	TransactionHash: "token_transfers.transaction_hash",
	LogIndex:        "token_transfers.log_index",
	BlockTimestamp:  "token_transfers.block_timestamp",
	UpdatedAt:       "token_transfers.updated_at",
	ChainID:         "token_transfers.chain_id",
}

// Generated where

type whereHelper__byte struct{ field string }

func (w whereHelper__byte) EQ(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelper__byte) NEQ(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelper__byte) LT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelper__byte) LTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelper__byte) GT(x []byte) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelper__byte) GTE(x []byte) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

type whereHelpertypes_Decimal struct{ field string }

func (w whereHelpertypes_Decimal) EQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_Decimal) NEQ(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_Decimal) LT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_Decimal) LTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_Decimal) GT(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_Decimal) GTE(x types.Decimal) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var TokenTransferWhere = struct {
	AddressFrom     whereHelper__byte
	AddressTo       whereHelper__byte
	Amount          whereHelpertypes_Decimal
	TransactionHash whereHelper__byte
	LogIndex        whereHelperint
	BlockTimestamp  whereHelpertime_Time
	UpdatedAt       whereHelpertime_Time
	ChainID         whereHelperstring
}{
	AddressFrom:     whereHelper__byte{field: "\"rewards_api\".\"token_transfers\".\"address_from\""},
	AddressTo:       whereHelper__byte{field: "\"rewards_api\".\"token_transfers\".\"address_to\""},
	Amount:          whereHelpertypes_Decimal{field: "\"rewards_api\".\"token_transfers\".\"amount\""},
	TransactionHash: whereHelper__byte{field: "\"rewards_api\".\"token_transfers\".\"transaction_hash\""},
	LogIndex:        whereHelperint{field: "\"rewards_api\".\"token_transfers\".\"log_index\""},
	BlockTimestamp:  whereHelpertime_Time{field: "\"rewards_api\".\"token_transfers\".\"block_timestamp\""},
	UpdatedAt:       whereHelpertime_Time{field: "\"rewards_api\".\"token_transfers\".\"updated_at\""},
	ChainID:         whereHelperstring{field: "\"rewards_api\".\"token_transfers\".\"chain_id\""},
}

// TokenTransferRels is where relationship names are stored.
var TokenTransferRels = struct {
}{}

// tokenTransferR is where relationships are stored.
type tokenTransferR struct {
}

// NewStruct creates a new relationship struct
func (*tokenTransferR) NewStruct() *tokenTransferR {
	return &tokenTransferR{}
}

// tokenTransferL is where Load methods for each relationship are stored.
type tokenTransferL struct{}

var (
	tokenTransferAllColumns            = []string{"address_from", "address_to", "amount", "transaction_hash", "log_index", "block_timestamp", "updated_at", "chain_id"}
	tokenTransferColumnsWithoutDefault = []string{"address_from", "address_to", "amount", "transaction_hash", "log_index", "block_timestamp", "chain_id"}
	tokenTransferColumnsWithDefault    = []string{"updated_at"}
	tokenTransferPrimaryKeyColumns     = []string{"transaction_hash", "log_index", "chain_id"}
	tokenTransferGeneratedColumns      = []string{}
)

type (
	// TokenTransferSlice is an alias for a slice of pointers to TokenTransfer.
	// This should almost always be used instead of []TokenTransfer.
	TokenTransferSlice []*TokenTransfer
	// TokenTransferHook is the signature for custom TokenTransfer hook methods
	TokenTransferHook func(context.Context, boil.ContextExecutor, *TokenTransfer) error

	tokenTransferQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	tokenTransferType                 = reflect.TypeOf(&TokenTransfer{})
	tokenTransferMapping              = queries.MakeStructMapping(tokenTransferType)
	tokenTransferPrimaryKeyMapping, _ = queries.BindMapping(tokenTransferType, tokenTransferMapping, tokenTransferPrimaryKeyColumns)
	tokenTransferInsertCacheMut       sync.RWMutex
	tokenTransferInsertCache          = make(map[string]insertCache)
	tokenTransferUpdateCacheMut       sync.RWMutex
	tokenTransferUpdateCache          = make(map[string]updateCache)
	tokenTransferUpsertCacheMut       sync.RWMutex
	tokenTransferUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var tokenTransferAfterSelectHooks []TokenTransferHook

var tokenTransferBeforeInsertHooks []TokenTransferHook
var tokenTransferAfterInsertHooks []TokenTransferHook

var tokenTransferBeforeUpdateHooks []TokenTransferHook
var tokenTransferAfterUpdateHooks []TokenTransferHook

var tokenTransferBeforeDeleteHooks []TokenTransferHook
var tokenTransferAfterDeleteHooks []TokenTransferHook

var tokenTransferBeforeUpsertHooks []TokenTransferHook
var tokenTransferAfterUpsertHooks []TokenTransferHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *TokenTransfer) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tokenTransferAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *TokenTransfer) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tokenTransferBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *TokenTransfer) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tokenTransferAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *TokenTransfer) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tokenTransferBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *TokenTransfer) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tokenTransferAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *TokenTransfer) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tokenTransferBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *TokenTransfer) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tokenTransferAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *TokenTransfer) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tokenTransferBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *TokenTransfer) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range tokenTransferAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddTokenTransferHook registers your hook function for all future operations.
func AddTokenTransferHook(hookPoint boil.HookPoint, tokenTransferHook TokenTransferHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		tokenTransferAfterSelectHooks = append(tokenTransferAfterSelectHooks, tokenTransferHook)
	case boil.BeforeInsertHook:
		tokenTransferBeforeInsertHooks = append(tokenTransferBeforeInsertHooks, tokenTransferHook)
	case boil.AfterInsertHook:
		tokenTransferAfterInsertHooks = append(tokenTransferAfterInsertHooks, tokenTransferHook)
	case boil.BeforeUpdateHook:
		tokenTransferBeforeUpdateHooks = append(tokenTransferBeforeUpdateHooks, tokenTransferHook)
	case boil.AfterUpdateHook:
		tokenTransferAfterUpdateHooks = append(tokenTransferAfterUpdateHooks, tokenTransferHook)
	case boil.BeforeDeleteHook:
		tokenTransferBeforeDeleteHooks = append(tokenTransferBeforeDeleteHooks, tokenTransferHook)
	case boil.AfterDeleteHook:
		tokenTransferAfterDeleteHooks = append(tokenTransferAfterDeleteHooks, tokenTransferHook)
	case boil.BeforeUpsertHook:
		tokenTransferBeforeUpsertHooks = append(tokenTransferBeforeUpsertHooks, tokenTransferHook)
	case boil.AfterUpsertHook:
		tokenTransferAfterUpsertHooks = append(tokenTransferAfterUpsertHooks, tokenTransferHook)
	}
}

// One returns a single tokenTransfer record from the query.
func (q tokenTransferQuery) One(ctx context.Context, exec boil.ContextExecutor) (*TokenTransfer, error) {
	o := &TokenTransfer{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for token_transfers")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all TokenTransfer records from the query.
func (q tokenTransferQuery) All(ctx context.Context, exec boil.ContextExecutor) (TokenTransferSlice, error) {
	var o []*TokenTransfer

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to TokenTransfer slice")
	}

	if len(tokenTransferAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all TokenTransfer records in the query.
func (q tokenTransferQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count token_transfers rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q tokenTransferQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if token_transfers exists")
	}

	return count > 0, nil
}

// TokenTransfers retrieves all the records using an executor.
func TokenTransfers(mods ...qm.QueryMod) tokenTransferQuery {
	mods = append(mods, qm.From("\"rewards_api\".\"token_transfers\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"rewards_api\".\"token_transfers\".*"})
	}

	return tokenTransferQuery{q}
}

// FindTokenTransfer retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindTokenTransfer(ctx context.Context, exec boil.ContextExecutor, transactionHash []byte, logIndex int, chainID string, selectCols ...string) (*TokenTransfer, error) {
	tokenTransferObj := &TokenTransfer{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"rewards_api\".\"token_transfers\" where \"transaction_hash\"=$1 AND \"log_index\"=$2 AND \"chain_id\"=$3", sel,
	)

	q := queries.Raw(query, transactionHash, logIndex, chainID)

	err := q.Bind(ctx, exec, tokenTransferObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from token_transfers")
	}

	if err = tokenTransferObj.doAfterSelectHooks(ctx, exec); err != nil {
		return tokenTransferObj, err
	}

	return tokenTransferObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *TokenTransfer) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no token_transfers provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tokenTransferColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	tokenTransferInsertCacheMut.RLock()
	cache, cached := tokenTransferInsertCache[key]
	tokenTransferInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			tokenTransferAllColumns,
			tokenTransferColumnsWithDefault,
			tokenTransferColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(tokenTransferType, tokenTransferMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(tokenTransferType, tokenTransferMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"rewards_api\".\"token_transfers\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"rewards_api\".\"token_transfers\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into token_transfers")
	}

	if !cached {
		tokenTransferInsertCacheMut.Lock()
		tokenTransferInsertCache[key] = cache
		tokenTransferInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the TokenTransfer.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *TokenTransfer) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	tokenTransferUpdateCacheMut.RLock()
	cache, cached := tokenTransferUpdateCache[key]
	tokenTransferUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			tokenTransferAllColumns,
			tokenTransferPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update token_transfers, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"rewards_api\".\"token_transfers\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, tokenTransferPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(tokenTransferType, tokenTransferMapping, append(wl, tokenTransferPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update token_transfers row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for token_transfers")
	}

	if !cached {
		tokenTransferUpdateCacheMut.Lock()
		tokenTransferUpdateCache[key] = cache
		tokenTransferUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q tokenTransferQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for token_transfers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for token_transfers")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o TokenTransferSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tokenTransferPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"rewards_api\".\"token_transfers\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, tokenTransferPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in tokenTransfer slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all tokenTransfer")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *TokenTransfer) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no token_transfers provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(tokenTransferColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	tokenTransferUpsertCacheMut.RLock()
	cache, cached := tokenTransferUpsertCache[key]
	tokenTransferUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			tokenTransferAllColumns,
			tokenTransferColumnsWithDefault,
			tokenTransferColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			tokenTransferAllColumns,
			tokenTransferPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert token_transfers, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(tokenTransferPrimaryKeyColumns))
			copy(conflict, tokenTransferPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"rewards_api\".\"token_transfers\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(tokenTransferType, tokenTransferMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(tokenTransferType, tokenTransferMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert token_transfers")
	}

	if !cached {
		tokenTransferUpsertCacheMut.Lock()
		tokenTransferUpsertCache[key] = cache
		tokenTransferUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single TokenTransfer record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *TokenTransfer) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no TokenTransfer provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), tokenTransferPrimaryKeyMapping)
	sql := "DELETE FROM \"rewards_api\".\"token_transfers\" WHERE \"transaction_hash\"=$1 AND \"log_index\"=$2 AND \"chain_id\"=$3"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from token_transfers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for token_transfers")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q tokenTransferQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no tokenTransferQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from token_transfers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for token_transfers")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o TokenTransferSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(tokenTransferBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tokenTransferPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"rewards_api\".\"token_transfers\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, tokenTransferPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from tokenTransfer slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for token_transfers")
	}

	if len(tokenTransferAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *TokenTransfer) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindTokenTransfer(ctx, exec, o.TransactionHash, o.LogIndex, o.ChainID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *TokenTransferSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := TokenTransferSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), tokenTransferPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"rewards_api\".\"token_transfers\".* FROM \"rewards_api\".\"token_transfers\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, tokenTransferPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in TokenTransferSlice")
	}

	*o = slice

	return nil
}

// TokenTransferExists checks if the TokenTransfer row exists.
func TokenTransferExists(ctx context.Context, exec boil.ContextExecutor, transactionHash []byte, logIndex int, chainID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"rewards_api\".\"token_transfers\" where \"transaction_hash\"=$1 AND \"log_index\"=$2 AND \"chain_id\"=$3 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, transactionHash, logIndex, chainID)
	}
	row := exec.QueryRowContext(ctx, sql, transactionHash, logIndex, chainID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if token_transfers exists")
	}

	return exists, nil
}

// Exists checks if the TokenTransfer row exists.
func (o *TokenTransfer) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return TokenTransferExists(ctx, exec, o.TransactionHash, o.LogIndex, o.ChainID)
}
