// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// VinOverride is an object representing the database table.
type VinOverride struct {
	TokenID   int         `boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	Vin       string      `boil:"vin" json:"vin" toml:"vin" yaml:"vin"`
	Note      null.String `boil:"note" json:"note,omitempty" toml:"note" yaml:"note,omitempty"`
	CreatedAt time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *vinOverrideR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L vinOverrideL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VinOverrideColumns = struct {
	TokenID   string
	Vin       string
	Note      string
	CreatedAt string
}{
	TokenID:   "token_id",
	Vin:       "vin",
	Note:      "note",
	CreatedAt: "created_at",
}

var VinOverrideTableColumns = struct {
	TokenID   string
	Vin       string
	Note      string
	CreatedAt string
}{
	TokenID:   "vin_overrides.token_id",
	Vin:       "vin_overrides.vin",
	Note:      "vin_overrides.note",
	CreatedAt: "vin_overrides.created_at",
}

// Generated where

var VinOverrideWhere = struct {
	TokenID   whereHelperint
	Vin       whereHelperstring
	Note      whereHelpernull_String
	CreatedAt whereHelpertime_Time
}{
	TokenID:   whereHelperint{field: "\"rewards_api\".\"vin_overrides\".\"token_id\""},
	Vin:       whereHelperstring{field: "\"rewards_api\".\"vin_overrides\".\"vin\""},
	Note:      whereHelpernull_String{field: "\"rewards_api\".\"vin_overrides\".\"note\""},
	CreatedAt: whereHelpertime_Time{field: "\"rewards_api\".\"vin_overrides\".\"created_at\""},
}

// VinOverrideRels is where relationship names are stored.
var VinOverrideRels = struct {
}{}

// vinOverrideR is where relationships are stored.
type vinOverrideR struct {
}

// NewStruct creates a new relationship struct
func (*vinOverrideR) NewStruct() *vinOverrideR {
	return &vinOverrideR{}
}

// vinOverrideL is where Load methods for each relationship are stored.
type vinOverrideL struct{}

var (
	vinOverrideAllColumns            = []string{"token_id", "vin", "note", "created_at"}
	vinOverrideColumnsWithoutDefault = []string{"token_id", "vin", "note"}
	vinOverrideColumnsWithDefault    = []string{"created_at"}
	vinOverridePrimaryKeyColumns     = []string{"token_id"}
	vinOverrideGeneratedColumns      = []string{}
)

type (
	// VinOverrideSlice is an alias for a slice of pointers to VinOverride.
	// This should almost always be used instead of []VinOverride.
	VinOverrideSlice []*VinOverride
	// VinOverrideHook is the signature for custom VinOverride hook methods
	VinOverrideHook func(context.Context, boil.ContextExecutor, *VinOverride) error

	vinOverrideQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	vinOverrideType                 = reflect.TypeOf(&VinOverride{})
	vinOverrideMapping              = queries.MakeStructMapping(vinOverrideType)
	vinOverridePrimaryKeyMapping, _ = queries.BindMapping(vinOverrideType, vinOverrideMapping, vinOverridePrimaryKeyColumns)
	vinOverrideInsertCacheMut       sync.RWMutex
	vinOverrideInsertCache          = make(map[string]insertCache)
	vinOverrideUpdateCacheMut       sync.RWMutex
	vinOverrideUpdateCache          = make(map[string]updateCache)
	vinOverrideUpsertCacheMut       sync.RWMutex
	vinOverrideUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var vinOverrideAfterSelectMu sync.Mutex
var vinOverrideAfterSelectHooks []VinOverrideHook

var vinOverrideBeforeInsertMu sync.Mutex
var vinOverrideBeforeInsertHooks []VinOverrideHook
var vinOverrideAfterInsertMu sync.Mutex
var vinOverrideAfterInsertHooks []VinOverrideHook

var vinOverrideBeforeUpdateMu sync.Mutex
var vinOverrideBeforeUpdateHooks []VinOverrideHook
var vinOverrideAfterUpdateMu sync.Mutex
var vinOverrideAfterUpdateHooks []VinOverrideHook

var vinOverrideBeforeDeleteMu sync.Mutex
var vinOverrideBeforeDeleteHooks []VinOverrideHook
var vinOverrideAfterDeleteMu sync.Mutex
var vinOverrideAfterDeleteHooks []VinOverrideHook

var vinOverrideBeforeUpsertMu sync.Mutex
var vinOverrideBeforeUpsertHooks []VinOverrideHook
var vinOverrideAfterUpsertMu sync.Mutex
var vinOverrideAfterUpsertHooks []VinOverrideHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *VinOverride) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vinOverrideAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *VinOverride) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vinOverrideBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *VinOverride) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vinOverrideAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *VinOverride) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vinOverrideBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *VinOverride) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vinOverrideAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *VinOverride) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vinOverrideBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *VinOverride) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vinOverrideAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *VinOverride) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vinOverrideBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *VinOverride) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range vinOverrideAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVinOverrideHook registers your hook function for all future operations.
func AddVinOverrideHook(hookPoint boil.HookPoint, vinOverrideHook VinOverrideHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		vinOverrideAfterSelectMu.Lock()
		vinOverrideAfterSelectHooks = append(vinOverrideAfterSelectHooks, vinOverrideHook)
		vinOverrideAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		vinOverrideBeforeInsertMu.Lock()
		vinOverrideBeforeInsertHooks = append(vinOverrideBeforeInsertHooks, vinOverrideHook)
		vinOverrideBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		vinOverrideAfterInsertMu.Lock()
		vinOverrideAfterInsertHooks = append(vinOverrideAfterInsertHooks, vinOverrideHook)
		vinOverrideAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		vinOverrideBeforeUpdateMu.Lock()
		vinOverrideBeforeUpdateHooks = append(vinOverrideBeforeUpdateHooks, vinOverrideHook)
		vinOverrideBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		vinOverrideAfterUpdateMu.Lock()
		vinOverrideAfterUpdateHooks = append(vinOverrideAfterUpdateHooks, vinOverrideHook)
		vinOverrideAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		vinOverrideBeforeDeleteMu.Lock()
		vinOverrideBeforeDeleteHooks = append(vinOverrideBeforeDeleteHooks, vinOverrideHook)
		vinOverrideBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		vinOverrideAfterDeleteMu.Lock()
		vinOverrideAfterDeleteHooks = append(vinOverrideAfterDeleteHooks, vinOverrideHook)
		vinOverrideAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		vinOverrideBeforeUpsertMu.Lock()
		vinOverrideBeforeUpsertHooks = append(vinOverrideBeforeUpsertHooks, vinOverrideHook)
		vinOverrideBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		vinOverrideAfterUpsertMu.Lock()
		vinOverrideAfterUpsertHooks = append(vinOverrideAfterUpsertHooks, vinOverrideHook)
		vinOverrideAfterUpsertMu.Unlock()
	}
}

// One returns a single vinOverride record from the query.
func (q vinOverrideQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VinOverride, error) {
	o := &VinOverride{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for vin_overrides")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all VinOverride records from the query.
func (q vinOverrideQuery) All(ctx context.Context, exec boil.ContextExecutor) (VinOverrideSlice, error) {
	var o []*VinOverride

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to VinOverride slice")
	}

	if len(vinOverrideAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all VinOverride records in the query.
func (q vinOverrideQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count vin_overrides rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q vinOverrideQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if vin_overrides exists")
	}

	return count > 0, nil
}

// VinOverrides retrieves all the records using an executor.
func VinOverrides(mods ...qm.QueryMod) vinOverrideQuery {
	mods = append(mods, qm.From("\"rewards_api\".\"vin_overrides\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"rewards_api\".\"vin_overrides\".*"})
	}

	return vinOverrideQuery{q}
}

// FindVinOverride retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVinOverride(ctx context.Context, exec boil.ContextExecutor, tokenID int, selectCols ...string) (*VinOverride, error) {
	vinOverrideObj := &VinOverride{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"rewards_api\".\"vin_overrides\" where \"token_id\"=$1", sel,
	)

	q := queries.Raw(query, tokenID)

	err := q.Bind(ctx, exec, vinOverrideObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from vin_overrides")
	}

	if err = vinOverrideObj.doAfterSelectHooks(ctx, exec); err != nil {
		return vinOverrideObj, err
	}

	return vinOverrideObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VinOverride) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no vin_overrides provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vinOverrideColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	vinOverrideInsertCacheMut.RLock()
	cache, cached := vinOverrideInsertCache[key]
	vinOverrideInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			vinOverrideAllColumns,
			vinOverrideColumnsWithDefault,
			vinOverrideColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(vinOverrideType, vinOverrideMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(vinOverrideType, vinOverrideMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"rewards_api\".\"vin_overrides\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"rewards_api\".\"vin_overrides\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into vin_overrides")
	}

	if !cached {
		vinOverrideInsertCacheMut.Lock()
		vinOverrideInsertCache[key] = cache
		vinOverrideInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the VinOverride.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *VinOverride) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	vinOverrideUpdateCacheMut.RLock()
	cache, cached := vinOverrideUpdateCache[key]
	vinOverrideUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			vinOverrideAllColumns,
			vinOverridePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update vin_overrides, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"rewards_api\".\"vin_overrides\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, vinOverridePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(vinOverrideType, vinOverrideMapping, append(wl, vinOverridePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update vin_overrides row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for vin_overrides")
	}

	if !cached {
		vinOverrideUpdateCacheMut.Lock()
		vinOverrideUpdateCache[key] = cache
		vinOverrideUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q vinOverrideQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for vin_overrides")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for vin_overrides")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VinOverrideSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vinOverridePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"rewards_api\".\"vin_overrides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, vinOverridePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in vinOverride slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all vinOverride")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VinOverride) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no vin_overrides provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vinOverrideColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	vinOverrideUpsertCacheMut.RLock()
	cache, cached := vinOverrideUpsertCache[key]
	vinOverrideUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			vinOverrideAllColumns,
			vinOverrideColumnsWithDefault,
			vinOverrideColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			vinOverrideAllColumns,
			vinOverridePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert vin_overrides, could not build update column list")
		}

		ret := strmangle.SetComplement(vinOverrideAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(vinOverridePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert vin_overrides, could not build conflict column list")
			}

			conflict = make([]string, len(vinOverridePrimaryKeyColumns))
			copy(conflict, vinOverridePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"rewards_api\".\"vin_overrides\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(vinOverrideType, vinOverrideMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(vinOverrideType, vinOverrideMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert vin_overrides")
	}

	if !cached {
		vinOverrideUpsertCacheMut.Lock()
		vinOverrideUpsertCache[key] = cache
		vinOverrideUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single VinOverride record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *VinOverride) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no VinOverride provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), vinOverridePrimaryKeyMapping)
	sql := "DELETE FROM \"rewards_api\".\"vin_overrides\" WHERE \"token_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from vin_overrides")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for vin_overrides")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q vinOverrideQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no vinOverrideQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vin_overrides")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vin_overrides")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VinOverrideSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(vinOverrideBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vinOverridePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"rewards_api\".\"vin_overrides\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vinOverridePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from vinOverride slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for vin_overrides")
	}

	if len(vinOverrideAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *VinOverride) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVinOverride(ctx, exec, o.TokenID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VinOverrideSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VinOverrideSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vinOverridePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"rewards_api\".\"vin_overrides\".* FROM \"rewards_api\".\"vin_overrides\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vinOverridePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VinOverrideSlice")
	}

	*o = slice

	return nil
}

// VinOverrideExists checks if the VinOverride row exists.
func VinOverrideExists(ctx context.Context, exec boil.ContextExecutor, tokenID int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"rewards_api\".\"vin_overrides\" where \"token_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, tokenID)
	}
	row := exec.QueryRowContext(ctx, sql, tokenID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if vin_overrides exists")
	}

	return exists, nil
}

// Exists checks if the VinOverride row exists.
func (o *VinOverride) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return VinOverrideExists(ctx, exec, o.TokenID)
}
